CREATE TABLE "SYS_DICTIONARIES"  (
   "ID"                 VARCHAR2(38)                    NOT NULL,
   "CODE"               VARCHAR2(50)                    NOT NULL,
   "NAME"               VARCHAR2(150),
   "DESCRIPTION"        VARCHAR2(1000),
   "IS_DELETE"          SMALLINT                       DEFAULT 0 NOT NULL
      CONSTRAINT CKC_IS_DELETE_DIC CHECK ("IS_DELETE" IN (0,1)),
   CONSTRAINT PK_SYS_DICTIONARIES PRIMARY KEY ("ID")
);

COMMENT ON TABLE "SYS_DICTIONARIES" IS
'数据字典表';

COMMENT ON COLUMN "SYS_DICTIONARIES"."ID" IS
'字典标识';

COMMENT ON COLUMN "SYS_DICTIONARIES"."CODE" IS
'字典编号';

COMMENT ON COLUMN "SYS_DICTIONARIES"."NAME" IS
'字典名称';

COMMENT ON COLUMN "SYS_DICTIONARIES"."DESCRIPTION" IS
'字典描述';

COMMENT ON COLUMN "SYS_DICTIONARIES"."IS_DELETE" IS
'是否已删除';

CREATE UNIQUE INDEX "IDX_SYS_DICTIONARIES_CODE" ON "SYS_DICTIONARIES" (
   "CODE" ASC
);

CREATE TABLE "SYS_DICTIONARY_ITEMS"  (
   "ID"                 VARCHAR2(38)                    NOT NULL,
   "CODE"               VARCHAR2(50)                    NOT NULL,
   "TEXT"               VARCHAR2(300)                   NOT NULL,
   "DICTIONARY_ID"      VARCHAR2(38)                    NOT NULL,
   "PARENT"             VARCHAR2(38),
   "STATUS"             VARCHAR2(10)                   DEFAULT 'enabled' NOT NULL
      CONSTRAINT CKC_STATUS_SYS_DICT CHECK ("STATUS" IN ('enabled','disabled')),
   "ORDER_ID"           INTEGER                        DEFAULT 0 NOT NULL,
   "DESCRIPTION"        VARCHAR2(1000),
   "IS_DELETE"          SMALLINT                       DEFAULT 0 NOT NULL
      CONSTRAINT CKC_IS_DELETE_DICT_ITEM CHECK ("IS_DELETE" IN (0,1)),
   CONSTRAINT PK_SYS_DICTIONARY_ITEMS PRIMARY KEY ("ID")
);

COMMENT ON TABLE "SYS_DICTIONARY_ITEMS" IS
'数据字典项表';

COMMENT ON COLUMN "SYS_DICTIONARY_ITEMS"."ID" IS
'字典项标识';

COMMENT ON COLUMN "SYS_DICTIONARY_ITEMS"."CODE" IS
'字典项代号';

COMMENT ON COLUMN "SYS_DICTIONARY_ITEMS"."TEXT" IS
'字典项文本';

COMMENT ON COLUMN "SYS_DICTIONARY_ITEMS"."DICTIONARY_ID" IS
'字典标识';

COMMENT ON COLUMN "SYS_DICTIONARY_ITEMS"."PARENT" IS
'父亲数据字典项标识';

COMMENT ON COLUMN "SYS_DICTIONARY_ITEMS"."STATUS" IS
'字典项状态（可用和不可用）';

COMMENT ON COLUMN "SYS_DICTIONARY_ITEMS"."ORDER_ID" IS
'字典项顺序';

COMMENT ON COLUMN "SYS_DICTIONARY_ITEMS"."DESCRIPTION" IS
'字典项描述';

COMMENT ON COLUMN "SYS_DICTIONARY_ITEMS"."IS_DELETE" IS
'是否删除';

CREATE INDEX "FK_SYS_DICTIONARIES_DICTID" ON "SYS_DICTIONARY_ITEMS" (
   "DICTIONARY_ID" ASC
);

CREATE UNIQUE INDEX "IDX_SYS_DICTIONAYITEMS_CODE" ON "SYS_DICTIONARY_ITEMS" (
   "CODE" ASC,
   "DICTIONARY_ID" ASC
);

ALTER TABLE "SYS_DICTIONARY_ITEMS"
   ADD CONSTRAINT FK_SYS_DICT_REFERENCE_SYS_DICT FOREIGN KEY ("PARENT")
      REFERENCES "SYS_DICTIONARY_ITEMS" ("ID");

ALTER TABLE "SYS_DICTIONARY_ITEMS"
   ADD CONSTRAINT FK_DATA_DICTIONARY_REFERE FOREIGN KEY ("DICTIONARY_ID")
      REFERENCES "SYS_DICTIONARIES" ("ID")
      ON DELETE CASCADE;

