CREATE TABLE SYS_PORTAL  (
   "CODE"               VARCHAR2(30)                    NOT NULL,
   "TITLE"              VARCHAR2(300),
   "FOOTER"             VARCHAR2(300),
   "LOGO_URL"           VARCHAR2(300),
   "LAYOUT_ID"          VARCHAR2(38),
   CONSTRAINT PK_SYS_PORTAL PRIMARY KEY ("CODE")
);

COMMENT ON TABLE SYS_PORTAL IS
'记录系统所有的门户信息配置';

COMMENT ON COLUMN SYS_PORTAL."CODE" IS
'门户编码';

COMMENT ON COLUMN SYS_PORTAL."TITLE" IS
'门户标题';

COMMENT ON COLUMN SYS_PORTAL."FOOTER" IS
'门户页脚';

COMMENT ON COLUMN SYS_PORTAL."LOGO_URL" IS
'门户Logo';

COMMENT ON COLUMN SYS_PORTAL."LAYOUT_ID" IS
'布局标识';

CREATE TABLE SYS_PORTAL_LAYOUT  (
   "ID"                 VARCHAR2(38)                    NOT NULL,
   "NAME"               VARCHAR2(30)                    NOT NULL,
   "THUMBNAIL"          VARCHAR2(300),
   "URL"                VARCHAR2(300)                   NOT NULL,
   "DESCRIPTION"        VARCHAR2(300),
   CONSTRAINT PK_SYS_PORTAL_LAYOUT PRIMARY KEY ("ID")
);

COMMENT ON TABLE SYS_PORTAL_LAYOUT IS
'系统门户布局表';

COMMENT ON COLUMN SYS_PORTAL_LAYOUT."ID" IS
'布局标识';

COMMENT ON COLUMN SYS_PORTAL_LAYOUT."NAME" IS
'布局名称';

COMMENT ON COLUMN SYS_PORTAL_LAYOUT."THUMBNAIL" IS
'布局图标';

COMMENT ON COLUMN SYS_PORTAL_LAYOUT."URL" IS
'布局访问地址';

COMMENT ON COLUMN SYS_PORTAL_LAYOUT."DESCRIPTION" IS
'布局描述';

CREATE TABLE SYS_SHORTCUT_KEY  (
   "ID"                 VARCHAR2(38)                    NOT NULL,
   "PORTAL_CODE"        VARCHAR2(30)                    NOT NULL,
   "NAME"               VARCHAR2(30)                    NOT NULL,
   "THUMBNAIL"          VARCHAR2(300)                   NOT NULL,
   "TARGET"             VARCHAR2(10),
   "URL"                VARCHAR2(300)                   NOT NULL,
   "PERMISSION_CODE"    VARCHAR2(50),
   "DISPLAY_ORDER"      INTEGER                        DEFAULT 0 NOT NULL,
   CONSTRAINT PK_SYS_SHORTCUT_KEY PRIMARY KEY ("ID")
);

COMMENT ON TABLE SYS_SHORTCUT_KEY IS
'存储系统的快捷键';

COMMENT ON COLUMN SYS_SHORTCUT_KEY."ID" IS
'快捷键标识';

COMMENT ON COLUMN SYS_SHORTCUT_KEY."PORTAL_CODE" IS
'门户编码';

COMMENT ON COLUMN SYS_SHORTCUT_KEY."NAME" IS
'快捷键名称';

COMMENT ON COLUMN SYS_SHORTCUT_KEY."THUMBNAIL" IS
'图标';

COMMENT ON COLUMN SYS_SHORTCUT_KEY."TARGET" IS
'打开容器';

COMMENT ON COLUMN SYS_SHORTCUT_KEY."URL" IS
'链接或js';

COMMENT ON COLUMN SYS_SHORTCUT_KEY."PERMISSION_CODE" IS
'权限编码';

COMMENT ON COLUMN SYS_SHORTCUT_KEY."DISPLAY_ORDER" IS
'显示顺序';

CREATE INDEX FK_SYS_SHOTCUT_KEY ON SYS_SHORTCUT_KEY (
   "PORTAL_CODE" ASC
);

CREATE TABLE SYS_SITE_MAP  (
   "ID"                 VARCHAR2(38)                    NOT NULL,
   "PARENT_ID"          VARCHAR2(38),
   "PORTAL_CODE"        VARCHAR2(30)                   DEFAULT 'default',
   "PLUGIN_CODE"        VARCHAR2(30),
   "ORDER"              NUMBER                         DEFAULT 1 NOT NULL,
   "URL"                VARCHAR2(1000),
   "TITLE"              VARCHAR2(50)                    NOT NULL,
   "TARGET"             VARCHAR2(30),
   "THUMBNAIL_SMALL"    VARCHAR2(300),
   "THUMBNAIL_MIDDLE"   VARCHAR2(300),
   "THUMBNAIL_LARGE"    VARCHAR2(300),
   CONSTRAINT PK_SYS_SITE_MAP PRIMARY KEY ("ID")
);

COMMENT ON TABLE SYS_SITE_MAP IS
'系统菜单配置表';

COMMENT ON COLUMN SYS_SITE_MAP."ID" IS
'菜单标识';

COMMENT ON COLUMN SYS_SITE_MAP."PARENT_ID" IS
'父菜单标识';

COMMENT ON COLUMN SYS_SITE_MAP."PORTAL_CODE" IS
'门户编码';

COMMENT ON COLUMN SYS_SITE_MAP."PLUGIN_CODE" IS
'菜单来源插件';

COMMENT ON COLUMN SYS_SITE_MAP."ORDER" IS
'顺序';

COMMENT ON COLUMN SYS_SITE_MAP."URL" IS
'菜单对应的URL路径';

COMMENT ON COLUMN SYS_SITE_MAP."TITLE" IS
'菜单标题';

COMMENT ON COLUMN SYS_SITE_MAP."TARGET" IS
'菜单对应内容渲染的容器';

COMMENT ON COLUMN SYS_SITE_MAP."THUMBNAIL_SMALL" IS
'菜单小图标';

COMMENT ON COLUMN SYS_SITE_MAP."THUMBNAIL_MIDDLE" IS
'菜单中图标';

COMMENT ON COLUMN SYS_SITE_MAP."THUMBNAIL_LARGE" IS
'菜单大图标';

CREATE INDEX FK_SYS_SITE_MAP ON SYS_SITE_MAP (
   "PORTAL_CODE" ASC
);

CREATE INDEX FK_SYS_SITE_MAP_PARENT ON SYS_SITE_MAP (
   "PARENT_ID" ASC
);

ALTER TABLE SYS_SHORTCUT_KEY
   ADD CONSTRAINT FK_SYS_SHOR_REFERENCE_SYS_PORT FOREIGN KEY ("PORTAL_CODE")
      REFERENCES SYS_PORTAL ("CODE")
      ON DELETE CASCADE;

ALTER TABLE SYS_SITE_MAP
   ADD CONSTRAINT FK_SYS_SITE_REFERENCE_SYS_SITE FOREIGN KEY ("PARENT_ID")
      REFERENCES SYS_SITE_MAP ("ID")
      ON DELETE CASCADE;

ALTER TABLE SYS_SITE_MAP
   ADD CONSTRAINT FK_SYS_SITE_REFERENCE_SYS_PORT FOREIGN KEY ("PORTAL_CODE")
      REFERENCES SYS_PORTAL ("CODE")
      ON DELETE CASCADE;

