CREATE TABLE SYS_PROFILE  (
   "ID"                 VARCHAR2(38)                    NOT NULL,
   "NAME"               VARCHAR2(30)                    NOT NULL,
   "DESCRIPTION"        VARCHAR2(300),
   "ACTIVATE"           SMALLINT                       DEFAULT 0 NOT NULL,
   "GLOBAL"             SMALLINT                       DEFAULT 0 NOT NULL,
   CONSTRAINT PK_SYS_PROFILE PRIMARY KEY ("ID"),
   CONSTRAINT AK_KEY_8_SYS_PROF UNIQUE ("NAME")
);

COMMENT ON TABLE SYS_PROFILE IS
'系统配置';

COMMENT ON COLUMN SYS_PROFILE."ID" IS
'profile标识';

COMMENT ON COLUMN SYS_PROFILE."NAME" IS
'名称';

COMMENT ON COLUMN SYS_PROFILE."DESCRIPTION" IS
'描述';

COMMENT ON COLUMN SYS_PROFILE."ACTIVATE" IS
'是否激活 0 未激活 1 激活  非公共的配置只能有一个是激活的';

COMMENT ON COLUMN SYS_PROFILE."GLOBAL" IS
'是否公共 0 非公共 1 公共   公共的可以有多个是公共的';

CREATE INDEX IDX_SYS_PROFILE_02 ON SYS_PROFILE (
   "ACTIVATE" ASC
);

CREATE INDEX IDX_SYS_PROFILE_03 ON SYS_PROFILE (
   "GLOBAL" ASC
);

CREATE TABLE SYS_PROFILE_PARAMETER  (
   "ID"                 VARCHAR2(38)                    NOT NULL,
   "PROFILE_ID"         VARCHAR2(38)                    NOT NULL,
   "NAME"               VARCHAR2(50)                    NOT NULL,
   "VALUE"              VARCHAR2(50),
   "DESCRIPTION"        VARCHAR2(300),
   CONSTRAINT PK_SYS_PROFILE_PARAMETER PRIMARY KEY ("ID"),
   CONSTRAINT AK_KEY_6_SYS_PROF UNIQUE ("PROFILE_ID", "NAME")
);

COMMENT ON TABLE SYS_PROFILE_PARAMETER IS
'系统配置下的参数';

COMMENT ON COLUMN SYS_PROFILE_PARAMETER."ID" IS
'参数标识';

COMMENT ON COLUMN SYS_PROFILE_PARAMETER."PROFILE_ID" IS
'所属配置';

COMMENT ON COLUMN SYS_PROFILE_PARAMETER."NAME" IS
'参数名称';

COMMENT ON COLUMN SYS_PROFILE_PARAMETER."VALUE" IS
'参数值';

COMMENT ON COLUMN SYS_PROFILE_PARAMETER."DESCRIPTION" IS
'参数描述';

ALTER TABLE SYS_PROFILE_PARAMETER
   ADD CONSTRAINT FK_SYS_PROF_REFERENCE_SYS_PROF FOREIGN KEY ("PROFILE_ID")
      REFERENCES SYS_PROFILE ("ID")
      ON DELETE CASCADE;

