CREATE TABLE SYS_DICTIONARIES
(
   ID                   VARCHAR(38) NOT NULL COMMENT '字典标识',
   CODE                 VARCHAR(50) NOT NULL COMMENT '字典编号',
   NAME                 VARCHAR(150) COMMENT '字典名称',
   DESCRIPTION          VARCHAR(1000) COMMENT '字典描述',
   IS_DELETE            SMALLINT NOT NULL DEFAULT 0 COMMENT '是否已删除',
   PRIMARY KEY (ID)
);

ALTER TABLE SYS_DICTIONARIES COMMENT '数据字典表';

CREATE UNIQUE INDEX IDX_SYS_DICTIONARIES_CODE ON SYS_DICTIONARIES
(
   CODE
);

CREATE TABLE SYS_DICTIONARY_ITEMS
(
   ID                   VARCHAR(38) NOT NULL COMMENT '字典项标识',
   CODE                 VARCHAR(50) NOT NULL COMMENT '字典项代号',
   TEXT                 VARCHAR(300) NOT NULL COMMENT '字典项文本',
   DICTIONARY_ID        VARCHAR(38) NOT NULL COMMENT '字典标识',
   PARENT               VARCHAR(38) COMMENT '父亲数据字典项标识',
   STATUS               VARCHAR(10) NOT NULL DEFAULT 'enabled' COMMENT '字典项状态（可用和不可用）',
   ORDER_ID             INT NOT NULL DEFAULT 0 COMMENT '字典项顺序',
   DESCRIPTION          VARCHAR(1000) COMMENT '字典项描述',
   IS_DELETE            SMALLINT NOT NULL DEFAULT 0 COMMENT '是否删除',
   PRIMARY KEY (ID)
);

ALTER TABLE SYS_DICTIONARY_ITEMS COMMENT '数据字典项表';

CREATE UNIQUE INDEX IDX_SYS_DICTIONAYITEMS_CODE ON SYS_DICTIONARY_ITEMS
(
   CODE,
   DICTIONARY_ID
);

ALTER TABLE SYS_DICTIONARY_ITEMS ADD CONSTRAINT FK_REFERENCE_32 FOREIGN KEY (PARENT)
      REFERENCES SYS_DICTIONARY_ITEMS (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE SYS_DICTIONARY_ITEMS ADD CONSTRAINT FK_DATA_DICTIONARY_REFERE FOREIGN KEY (DICTIONARY_ID)
      REFERENCES SYS_DICTIONARIES (ID) ON DELETE CASCADE ON UPDATE RESTRICT;

