CREATE TABLE SYS_PORTAL
(
   CODE                 VARCHAR(30) NOT NULL COMMENT '门户编码',
   TITLE                VARCHAR(300) COMMENT '门户标题',
   FOOTER               VARCHAR(300) COMMENT '门户页脚',
   LOGO_URL             VARCHAR(300) COMMENT '门户Logo',
   LAYOUT_ID            VARCHAR(38) COMMENT '布局标识',
   PRIMARY KEY (CODE)
);

ALTER TABLE SYS_PORTAL COMMENT '记录系统所有的门户信息配置';

CREATE TABLE SYS_PORTAL_LAYOUT
(
   ID                   VARCHAR(38) NOT NULL COMMENT '布局标识',
   NAME                 VARCHAR(30) NOT NULL COMMENT '布局名称',
   THUMBNAIL            VARCHAR(300) COMMENT '布局图标',
   URL                  VARCHAR(300) NOT NULL COMMENT '布局访问地址',
   DESCRIPTION          VARCHAR(300) COMMENT '布局描述',
   PRIMARY KEY (ID)
);

ALTER TABLE SYS_PORTAL_LAYOUT COMMENT '系统门户布局表';

CREATE TABLE SYS_SHORTCUT_KEY
(
   ID                   VARCHAR(38) NOT NULL COMMENT '快捷键标识',
   PORTAL_CODE          VARCHAR(30) NOT NULL COMMENT '门户编码',
   NAME                 VARCHAR(30) NOT NULL COMMENT '快捷键名称',
   THUMBNAIL            VARCHAR(300) NOT NULL COMMENT '图标',
   TARGET               VARCHAR(10) COMMENT '打开容器',
   URL                  VARCHAR(300) NOT NULL COMMENT '链接或js',
   PERMISSION_CODE      VARCHAR(50) COMMENT '权限编码',
   DISPLAY_ORDER        INT NOT NULL DEFAULT 0 COMMENT '显示顺序',
   PRIMARY KEY (ID),
   CONSTRAINT FK_REFERENCE_30 FOREIGN KEY (PORTAL_CODE)
      REFERENCES SYS_PORTAL (CODE) ON DELETE CASCADE ON UPDATE RESTRICT
);

ALTER TABLE SYS_SHORTCUT_KEY COMMENT '存储系统的快捷键';

CREATE TABLE SYS_SITE_MAP
(
   ID                   VARCHAR(38) NOT NULL COMMENT '菜单标识',
   PARENT_ID            VARCHAR(38) COMMENT '父菜单标识',
   PORTAL_CODE          VARCHAR(30) DEFAULT 'default' COMMENT '门户编码',
   PLUGIN_CODE          VARCHAR(30) COMMENT '菜单来源插件',
   `ORDER`              NUMERIC(8,0) NOT NULL DEFAULT 1 COMMENT '顺序',
   URL                  VARCHAR(1000) COMMENT '菜单对应的URL路径',
   TITLE                VARCHAR(50) NOT NULL COMMENT '菜单标题',
   TARGET               VARCHAR(30) COMMENT '菜单对应内容渲染的容器',
   THUMBNAIL_SMALL      VARCHAR(300) COMMENT '菜单小图标',
   THUMBNAIL_MIDDLE     VARCHAR(300) COMMENT '菜单中图标',
   THUMBNAIL_LARGE      VARCHAR(300) COMMENT '菜单大图标',
   PRIMARY KEY (ID),
   CONSTRAINT FK_REFERENCE_31 FOREIGN KEY (PORTAL_CODE)
      REFERENCES SYS_PORTAL (CODE) ON DELETE CASCADE ON UPDATE RESTRICT,
   CONSTRAINT FK_REFERENCE_25 FOREIGN KEY (PARENT_ID)
      REFERENCES SYS_SITE_MAP (ID) ON DELETE CASCADE ON UPDATE RESTRICT
);

ALTER TABLE SYS_SITE_MAP COMMENT '系统菜单配置表';

