CREATE TABLE SYS_PROFILE
(
   ID                   VARCHAR(38) NOT NULL COMMENT 'profile标识',
   NAME                 VARCHAR(30) NOT NULL COMMENT '名称',
   DESCRIPTION          VARCHAR(300) COMMENT '描述',
   ACTIVATE             SMALLINT NOT NULL DEFAULT 0 COMMENT '是否激活 0 未激活 1 激活  非公共的配置只能有一个是激活的',
   GLOBAL               SMALLINT NOT NULL DEFAULT 0 COMMENT '是否公共 0 非公共 1 公共   公共的可以有多个是公共的',
   PRIMARY KEY (ID),
   KEY AK_KEY_8_SYS_PROF (NAME)
);

ALTER TABLE SYS_PROFILE COMMENT '系统配置';

CREATE INDEX IDX_SYS_PROFILE_02 ON SYS_PROFILE
(
   ACTIVATE
);

CREATE INDEX IDX_SYS_PROFILE_03 ON SYS_PROFILE
(
   GLOBAL
);

CREATE TABLE SYS_PROFILE_PARAMETER
(
   ID                   VARCHAR(38) NOT NULL COMMENT '参数标识',
   PROFILE_ID           VARCHAR(38) NOT NULL COMMENT '所属配置',
   NAME                 VARCHAR(50) NOT NULL COMMENT '参数名称',
   VALUE                VARCHAR(50) COMMENT '参数值',
   DESCRIPTION          VARCHAR(300) COMMENT '参数描述',
   PRIMARY KEY (ID),
   KEY AK_KEY_6_SYS_PROF (PROFILE_ID, NAME)
);

ALTER TABLE SYS_PROFILE_PARAMETER COMMENT '系统配置下的参数';

ALTER TABLE SYS_PROFILE_PARAMETER ADD CONSTRAINT FK_REFERENCE_1 FOREIGN KEY (PROFILE_ID)
      REFERENCES SYS_PROFILE (ID) ON DELETE CASCADE;

